---
# requirements.yml
collections:
  # Docker collection for container management
  - name: community.docker
    version: ">=3.4.0"

  # General utilities
  - name: community.general
    version: ">=6.0.0"
