proxmox:
  hosts:
    server-1:
      ansible_host: 192.168.29.61
    server-2:
      ansible_host: 192.168.29.52
    server-3:
      ansible_host: 192.168.29.69
  vars:
    ansible_user: root
    ansible_ssh_private_key_file: ~/.ssh/id_rsa

homelab:
  hosts:
    homelab-server:
      ansible_host: 192.168.29.61
    homelab-server-2:
      ansible_host: 192.168.29.52
    homelab-server-3:
      ansible_host: 192.168.29.69
  vars:
    ansible_user: anon
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    homelab_user: anon
    homelab_domain: homelab.local

kubernetes:
  children:
    kubernetes-control-planes:
    kubernetes-worker-nodes:
  vars:
    ansible_user: anton
    ansible_ssh_private_key_file: ~/.ssh/id_rsa

kubernetes-control-planes:
  hosts:
    control-node-1:
      ansible_host: 192.168.29.239
    control-node-2:
      ansible_host: 192.168.29.204
kubernetes-worker-nodes:
  hosts:
    worker-node-1:
      ansible_host: 192.168.29.74
    worker-node-2:
      ansible_host: 192.168.29.213
  vars:
    # ansible_python_interpreter: /usr/bin/python3
  #   docker_compose_version: "2.21.0"

  #   # Service configuration
  #   services:
  #     portainer:
  #       enabled: true
  #       port: 9000
  #     jellyfin:
  #       enabled: true
  #       port: 8096
  #     nextcloud:
  #       enabled: true
  #       port: 8080
  #     homeassistant:
  #       enabled: false
  #       port: 8123
  #     grafana:
  #       enabled: true
  #       port: 3000
  #     prometheus:
  #       enabled: true
  #       port: 9090
