homelab:
  hosts:
    homelab-server:
      ansible_host: 192.168.29.197
      ansible_user: anon
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
  vars:
    homelab_user: anon
    homelab_domain: homelab.local

kubernetes:
  children:
    kubernetes-control-planes:
    kubernetes-worker-nodes:

kubernetes-control-planes:
  hosts:
    control-node-1:
      ansible_host: 192.168.29.239
      ansible_user: anton
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
    control-node-2:
      ansible_host: 192.168.29.204
      ansible_user: anton
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
kubernetes-worker-nodes:
  hosts:
    worker-node-1:
      ansible_host: 192.168.29.74
      ansible_user: anton
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
  vars:
    # ansible_python_interpreter: /usr/bin/python3
  #   docker_compose_version: "2.21.0"

  #   # Service configuration
  #   services:
  #     portainer:
  #       enabled: true
  #       port: 9000
  #     jellyfin:
  #       enabled: true
  #       port: 8096
  #     nextcloud:
  #       enabled: true
  #       port: 8080
  #     homeassistant:
  #       enabled: false
  #       port: 8123
  #     grafana:
  #       enabled: true
  #       port: 3000
  #     prometheus:
  #       enabled: true
  #       port: 9090
