- name: Comment out Proxmox Enterprise repo
  ansible.builtin.replace:
    path: /etc/apt/sources.list.d/pve-enterprise.list
    regexp: '^deb'
    replace: '#deb'
  ignore_errors: yes

- name: Comment out Ceph Enterprise repo
  ansible.builtin.replace:
    path: /etc/apt/sources.list.d/ceph.list
    regexp: '^deb'
    replace: '#deb'
  ignore_errors: yes

- name: Add Proxmox no-subscription repo
  ansible.builtin.apt_repository:
    repo: 'deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription'
    state: present
    filename: 'pve-no-subscription'