---
- name: Remove swapfile from /etc/fstab
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap
    - none

- name: Ensure swap is disabled
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Ensure net.ipv4.ip_forward is set
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    reload: yes
    sysctl_file: /etc/sysctl.d/k8s.conf