---
- include_tasks: disable-swap.yaml

- include_tasks: setup-control-plane.yaml
  when: inventory_hostname in groups["kubernetes-control-planes"]
- include_tasks: setup-worker-node.yaml
  when: inventory_hostname in groups["kubernetes-worker-nodes"]


- include_tasks: setup-tools.yaml

- include_tasks: setup-containerd.yaml

# - include_tasks: setup-node-weave-cni.yaml
