- name: Install containerd
  apt:
    name: containerd
    state: present
    update_cache: yes

- name: Create containerd configuration directory
  file:
    path: /etc/containerd
    state: directory
    mode: "0755"

- name: Create containerd configuration file
  shell: containerd config default > /etc/containerd/config.toml
  args:
    creates: /etc/containerd/config.toml
  changed_when: false

- name: Set SystemdCgroup = true in config.toml
  replace:
    path: /etc/containerd/config.toml
    regexp: '^(\s*)SystemdCgroup\s*=\s*false'
    replace: '\1SystemdCgroup = true'

- name: Restart containerd
  systemd:
    name: containerd
    state: restarted
    enabled: true
